# Generated by Django 4.0.3 on 2022-03-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
